version: '3.7'
services:
    nginx: 
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./config/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx-logs:/etc/nginx/logs/
        - ./build/client/:/etc/nginx/html/
      ports:
        - 8502:80
    haproxy:
      image: haproxy
      container_name: haproxy-proxy
      restart: unless-stopped
    #   network_mode: "host" # DO NOT USE ON MAC!    Required when running on Linux hosts.
      ports:
          - 443:443
          - 80:80
      volumes:
          - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
          - ./certs:/etc/ssl/
